services:
  speedtest:
    build:
      dockerfile: Dockerfile
    container_name: speedtest2ha
    environment:
      - MQTT_HOST=mqtt://mosquitto
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./test/:/mosquitto/config/
    ports:
      - 1883:1883
      - 9001:9001
